title: Shlomi's blog
description: "A personal blog"
author:
  name: "Shlomi Domnenko"
  email: "shlomidom@gmail.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

plugins_dir: _plugins

# Custom variables
owner : "Shlomi Domnenko"
year : "2023"
port: 52000
